[build]
    base="."
    publish="dist"
    command="vite build"

[functions]
    directory="netlify/functions"
    node_bundler="esbuild"

[[plugins]]
    package = "@netlify/plugin-emails"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[context.production.environment]
    MY_ENV = "production"
    VITE_SITE_URL = "https://apl.sabhapei.com"

[context.deploy-preview.environment]
    MY_ENV = "production"
    VITE_SITE_URL = "https://deploy-preview--apl-pei.netlify.app"

[context.branch-deploy.environment]
    MY_ENV = "branch-deploy"
    VITE_SITE_URL = "https://branch-deploy--apl-pei.netlify.app"

[context.dev.environment]
    MY_ENV = "dev"
    VITE_SITE_URL = "http://localhost:8888"